*** Reading local file: /opt/airflow/logs/increment/0_2/2021-08-30T04:03:05.174490+00:00/1.log
[2021-08-30 04:03:26,473] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: increment.0_2 2021-08-30T04:03:05.174490+00:00 [queued]>
[2021-08-30 04:03:26,481] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: increment.0_2 2021-08-30T04:03:05.174490+00:00 [queued]>
[2021-08-30 04:03:26,481] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-08-30 04:03:26,481] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2021-08-30 04:03:26,481] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-08-30 04:03:26,495] {taskinstance.py:1114} INFO - Executing <Task(_PythonDecoratedOperator): 0_2> on 2021-08-30T04:03:05.174490+00:00
[2021-08-30 04:03:26,497] {standard_task_runner.py:52} INFO - Started process 13 to run task
[2021-08-30 04:03:26,501] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'increment', '0_2', '2021-08-30T04:03:05.174490+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bad.py', '--cfg-path', '/tmp/tmp_gccolod', '--error-file', '/tmp/tmpzmvo5n_a']
[2021-08-30 04:03:26,501] {standard_task_runner.py:77} INFO - Job 4: Subtask 0_2
[2021-08-30 04:03:26,542] {logging_mixin.py:109} INFO - Running <TaskInstance: increment.0_2 2021-08-30T04:03:05.174490+00:00 [running]> on host increment02.82ebab73074e483da198c6fb93f2fc52
[2021-08-30 04:03:26,610] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=increment
AIRFLOW_CTX_TASK_ID=0_2
AIRFLOW_CTX_EXECUTION_DATE=2021-08-30T04:03:05.174490+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-30T04:03:05.174490+00:00
[2021-08-30 04:03:26,611] {logging_mixin.py:109} INFO - command:
[2021-08-30 04:03:26,611] {logging_mixin.py:109} INFO - kubectl run heoenev --rm -n freezebug --restart=Never -i --image=bash -- sleep 0.2
[2021-08-30 04:03:26,621] {sh.py:670} INFO - <Command "/bin/sh -c 'kubectl run heoenev --rm -n freezebug --restart=Never -i --image=bash -- sleep 0.2'", pid 14>: process started
[2021-08-30 04:03:29,040] {logging_mixin.py:109} INFO - result:
[2021-08-30 04:03:29,040] {logging_mixin.py:109} INFO - pod "heoenev" deleted
[2021-08-30 04:03:29,040] {logging_mixin.py:109} INFO - 
[2021-08-30 04:03:29,041] {python.py:151} INFO - Done. Returned value was: None
[2021-08-30 04:03:29,054] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=increment, task_id=0_2, execution_date=20210830T040305, start_date=20210830T040326, end_date=20210830T040329
[2021-08-30 04:03:29,078] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-08-30 04:03:29,106] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
